# Generated by Django 2.2.6 on 2020-05-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
